### ISSUE TITLE
Would like to contribute to this awesome project ☺️

### ISSUE THREAD

**Issue by unwls** [SumitNalavade/VS-Code-ReadMe-Editor#1]
Thank you very much for this nice extension!

Your styles are already really nice but my suggestions are below

1. Change mouse cursor to a pointer when the user hovers the clear button
2. Disable certain texts from being hovered
3. Change mouse cursor to a pointer when pressing the initial reload editor button

Just want to make this project better and prettier 😊

**Comment by SumitNalavade** [comment]
Thank you so much for bringing these issues to light… I’ll be sure to make an resolve then in an update!

**Comment by unwls** [comment]
@SumitNalavade Oh, I mean I could write up the code and make a pull request if you don't mind?

**Comment by SumitNalavade** [comment]
That’s even better go ahead!

**Comment by SumitNalavade** [comment]
Always looking for contributors!

**Comment by unwls** [comment]
@SumitNalavade I actually made this issue to get your confirmation about making a PR haha
but thanks for the opportunity!

**Comment by SumitNalavade** [comment]
Of course, I’ve assigned you to the issue

**Comment by unwls** [comment]
@SumitNalavade  cool thanks!

**Comment by SumitNalavade** [comment]
Patched in https://github.com/SumitNalavade/VS-Code-ReadMe-Editor/pull/3

Thanks to: https://github.com/unwls
