### ISSUE TITLE
Not able to install ReadMe editor

### ISSUE THREAD

**Issue by devauk** [SumitNalavade/VS-Code-ReadMe-Editor#4]
I am getting following error while trying to install the extension on Mac version of VS code

Unable to install 'sumitnalavade.vscode-readme-editor' extension because it is not compatible with the current version of VS Code (version 1.42.1).

Do we have any fix for this?

**Comment by SumitNalavade** [comment]
Thanks for letting me know, probably have to update NPM dependencies or something.
Should have a fix out soon

**Comment by SumitNalavade** [comment]
@devauk Seems like the most up to date version of VS Code is 1.72.
Can you try upgrading and see if it's still giving that error?

**Comment by devauk** [comment]
Thanks, will check and revert

**Comment by devauk** [comment]
It works with latest version (1.72). Thanks
